name: Build
on:
  pull_request:
    branches:
      - dev-test
  push:
    branches:
      - dev-test
jobs:
  pr-only:
    if: github.event_name == 'pull_request'
    name: Build for PR only
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          cache: pip
          python-version: "3.9"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run ruff
        run: ruff .
      - name: Test with pytest and pytest-cov omitting the test files
        run: pytest --cov=. --cov-config=.covconfig